import Head from "next/head";
import { Layout } from "components/layout";
import { Signup } from "components/form-signup";
import { Content } from "./styled";
import { Title } from "ui/typography";

export default function SigninPage() {
	return (
		<div>
			<Head>
				<title>Signup</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Layout>
				<Content>
					<Title>Signup</Title>
					<Signup />
				</Content>
			</Layout>
		</div>
	);
}
