import Head from "next/head";
import { useRouter } from "next/router";
import { Layout } from "components/layout";
import { SearchProductsPage } from "components/search-products-page";

export default function SearchQueryPage() {
	const router = useRouter();
	const query = JSON.stringify(router.query.query);

	return (
		<div>
			<Head>
				<title>Search</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Layout>
				<SearchProductsPage query={query} />
			</Layout>
		</div>
	);
}
