import Head from "next/head";
import { Layout } from "components/layout";

export default function LogOutPage() {
	return (
		<div>
			<Head>
				<title>My Free Market</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Layout>
				<h1>Logout</h1>
			</Layout>
		</div>
	);
}
