import Head from "next/head";
import { Layout } from "components/layout";
import { FeaturedProducts } from "components/featured-products";
import { Search } from "components/form-search";
import { Title } from "ui/typography";
import { Container, MainSection } from "./styled";

export default function Home() {
	return (
		<div>
			<Head>
				<title>My Free Market</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Layout>
				<Container>
					<MainSection>
						<Title>Find that product you want so much</Title>
						<Search />
					</MainSection>
					<FeaturedProducts />
				</Container>
			</Layout>
		</div>
	);
}
