import Head from "next/head";
import { Layout } from "components/layout";
import { Signin } from "components/form-signin";
import { Content } from "./styled";
import { Title } from "ui/typography";

export default function SigninPage() {
	return (
		<div>
			<Head>
				<title>My Free Market</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Layout>
				<Content>
					<Title>Signin</Title>
					<Signin />
				</Content>
			</Layout>
		</div>
	);
}
