import Head from "next/head";
import { Layout } from "ui/layout";
import { Container, Message } from "../../styles/thanks";
import { LargeText, SubTitle } from "ui/typography";
import { BigLogoIcon } from "ui/icons";

export default function ThanksPage() {
	return (
		<div>
			<Head>
				<title>Thanks</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Layout>
				<Container>
					<Message>
						<SubTitle color='var(--fucsia)'>Thank You!</SubTitle>
						<BigLogoIcon />
						<LargeText>
							Thank you for your trust. We will send the products to you as soon
							as possible.
						</LargeText>
					</Message>
				</Container>
			</Layout>
		</div>
	);
}
